create schema if not exists uskov_klyuchnikov;


create table if not exists uskov_klyuchnikov.drivers(
    driverId integer primary key generated by default as identity,
    firstName text not null,
    secondName text not null
);

create table if not exists uskov_klyuchnikov.customers(
    customerId integer primary key generated by default as identity,
    firstName text not null,
    secondName text not null
);

create table if not exists uskov_klyuchnikov.taxi(
    orderId integer primary key generated by default as identity,
    startDestination text not null,
    endDestination text not null,
    orderTime timestamp not null,
    carNumber text not null,
    driverId integer not null,
    customerId integer not null,
    status text not null,

    foreign key (driverId) references uskov_klyuchnikov.drivers(driverId),
    foreign key (customerId) references uskov_klyuchnikov.customers(customerId)
);
